name: 🤖 Cannot save fiddle
description: Problems with saving a fiddle. Report with no code provided will be removed.
title: "🤖 Cannot save fiddle"
labels: ["task"]
body:
  - type: input
    id: error-code
    attributes:
      label: Error code
      description: Error code
      placeholder: ERRW:0.6K0.3PU:1.0
      render: code
    validations:
      required: true
  - type: dropdown
    id: logged-in
    attributes:
      label: Were you logged in?
      options:
        - "Yes"
        - "No"
      render: code
    validations:
      required: true
  - type: input
    id: username
    attributes:
      label: Your username (if logged in)
      placeholder: j0hndoe
      render: code
    validations:
      required: false
  - type: textarea
    id: html
    attributes:
      label: Your HTML
      description: You have to provide at least one of HTML, CSS or JavaScript
      placeholder: |
        <p>...</p>
      render: html
    validations:
      required: false
  - type: textarea
    id: javascript
    attributes:
      label: Your JavaScript
      description: You have to provide at least one of HTML, CSS or JavaScript
      placeholder: |
        if (greet === "hello"){
          ...
        }
      render: javascript
    validations:
      required: false
  - type: textarea
    id: css
    attributes:
      label: Your CSS
      description: You have to provide at least one of HTML, CSS or JavaScript
      placeholder: |
        p {
          color: rgba(0, 0, 0, 0.1);
        }
      render: css
    validations:
      required: false
