name: Bug Report
description: Problems with saving a fiddle. Report with no code provided will be removed.
title: "Cannot save fiddle"
labels: ["task"]
body:
  - type: input
    id: error-code
    attributes:
      label: Error code
      description: Error code
      placeholder: ERRW:0.6K0.3PU:1.0
    validations:
      required: true
  - type: dropdown
    id: logged-in
    attributes:
      label: Were you logged in?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: input
    id: username
    attributes:
      label: Your username (if logged in)
      placeholder: j0hndoe
    validations:
      required: false
  - type: textarea
    id: html
    attributes:
      label: Your HTML
      description: You have to provide at least one of HTML, CSS or JavaScript
      placeholder: <p>...</p>
    validations:
      required: false
  - type: textarea
    id: javascript
    attributes:
      label: Your JavaScript
      description: You have to provide at least one of HTML, CSS or JavaScript
      placeholder: console.log(...)
    validations:
      required: false
  - type: textarea
    id: css
    attributes:
      label: Your CSS
      description: You have to provide at least one of HTML, CSS or JavaScript
      placeholder: p { ... }
    validations:
      required: false
